//
//  Constants.swift
//  On The Map
//
//  Created by Jena Grafton on 6/1/16.
//  Copyright © 2016 Bella Voce Productions. All rights reserved.
//

// MARK: - StudentClient (Constants)

extension StudentClient {
    
    // MARK: Constants
    struct Constants {
        
        // MARK: Udacity URLs
        static let ApiScheme = "https"
        static let ApiHost = "www.udacity.com"
        static let ApiPath = "/api"
        static let SessionAuthentication : String = "/session"
        
        // MARK: Parse API Keys
        static let ApiKey : String = "Api_Key" /* placeholder */
        static let ParseApiKey : String = "QrX47CA9cyuGewLdsL7o5Eb8iug6Em8ye0dnAbIr"
        static let RESTApiKey : String = "QuWThTdiRmTux3YaDseUSEpUKo7aBYM737yKd4gY"
        
        // MARK: Parse URLs
        static let ParseApiScheme = "https"
        static let ParseApiHost = "api.parse.com"
        static let ParseApiPath = "/1/classes"
        static let ParseMethod = "/StudentLocation"
        
    }
    
    /*
    // MARK: Methods
    struct Methods {
        
        // MARK: Account
        static let Account = "/account"
        static let AccountIDFavoriteMovies = "/account/{id}/favorite/movies"
        static let AccountIDFavorite = "/account/{id}/favorite"
        static let AccountIDWatchlistMovies = "/account/{id}/watchlist/movies"
        static let AccountIDWatchlist = "/account/{id}/watchlist"
        
        // MARK: Authentication
        static let AuthenticationTokenNew = "/authentication/token/new"
        static let AuthenticationSessionNew = "/authentication/session/new"
        
        // MARK: Search
        static let SearchMovie = "/search/movie"
        
        // MARK: Config
        static let Config = "/configuration"
        
    }
    
    // MARK: URL Keys
    struct URLKeys {
        static let UserID = "id"
    }
    */
    
    
    // MARK: Parameter Keys
    struct ParameterKeys {
        static let ApiKey = "Api_Key" /* placeholder */
        static let ParseLimit100 = "?limit=100"
        static let ParseSkip = "?limit=200&skip=400"
        static let ParseOrder = "?order=-updatedAt"
        
    }
    
    /*
    // MARK: JSON Body Keys
    struct JSONBodyKeys {
        static let MediaType = "media_type"
        static let MediaID = "media_id"
        static let Favorite = "favorite"
        static let Watchlist = "watchlist"
    }
    */
 
    // MARK: JSON Response Keys
    struct JSONResponseKeys {
        
        // MARK: General
        static let StatusMessage = "status_message"
        static let StatusCode = "status_code"
        
        // MARK: Authorization
        static let SessionCategory = "session"
        static let SessionID = "id"
        static let UserAccount = "account"
        static let UserAccountID = "key"
        
        // MARK: Account - Udacity account (user) ID
        static let UniqueKey = "uniqueKey"
        
        // MARK: Account - Parse auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
        static let ObjectID = "objectID"
        
        // MARK: StudentInfo
        static let FirstName = "firstName"
        static let LastName = "lastName"
        
        static let MapString = "mapString"
        static let MediaURL = "mediaURL"
        
        static let Latitude = "latitude"
        static let Longitude = "longitude"
       
        static let CreatedAt = "createdAt"
        static let UpdatedAt = "updatedAt"
        //static let ACL = "ACL"
        
        static let StudentResults = "results"
        
    }
    

}