//
//  Constants.swift
//  On The Map
//
//  Created by Jena Grafton on 6/1/16.
//  Copyright © 2016 Bella Voce Productions. All rights reserved.
//

// MARK: - StudentClient (Constants)

extension StudentClient {
    
    // MARK: Constants
    struct Constants {
        
        // MARK: Udacity URLs
        static let ApiScheme = "https"
        static let ApiHost = "www.udacity.com"
        static let ApiPath = "/api"
        static let SessionAuthentication : String = "/session"
        static let GetPublicUserData : String = "/users/"
        
        // MARK: Parse API Keys
        static let ParseApiKey : String = "QrX47CA9cyuGewLdsL7o5Eb8iug6Em8ye0dnAbIr"
        static let RESTApiKey : String = "QuWThTdiRmTux3YaDseUSEpUKo7aBYM737yKd4gY"
        
        // MARK: Parse URLs
        static let ParseApiScheme = "https"
        static let ParseApiHost = "parse.udacity.com"
        static let ParseApiPath = "/parse/classes"
        static let ParseMethod = "/StudentLocation"
        
    }
    
    
    // MARK: URL Keys
    struct URLKeys {
        static let UserID = "id"
    }
    
    // MARK: Parameter Keys
    struct ParameterKeys {
        static let ParseLimit100 = "limit"
        //static let ParseSkip = "?limit=200&skip=400"
        static let ParseOrder = "order"
        
    }
    
     
    // MARK: JSON Response Keys
    struct JSONResponseKeys {
        
        // MARK: General
        static let StatusMessage = "status_message"
        static let StatusCode = "status_code"
        
        // MARK: Authorization
        static let SessionCategory = "session"
        static let SessionID = "id"
        static let UserAccount = "account"
        static let UserAccountID = "key"
        
        //MARK: Udacity Get Public User Info
        static let User = "user"
        static let UserFirstName = "first_name"
        static let UserLastName = "last_name"
        
        // MARK: Account - Udacity account (user) ID
        static let UniqueKey = "uniqueKey"
        
        // MARK: Account - Parse auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
        static let ObjectID = "objectId"
        
        // MARK: StudentInfo
        static let FirstName = "firstName"
        static let LastName = "lastName"
        
        static let MapString = "mapString"
        static let MediaURL = "mediaURL"
        
        static let Latitude = "latitude"
        static let Longitude = "longitude"
       
        static let CreatedAt = "createdAt"
        static let UpdatedAt = "updatedAt"
        
        static let StudentResults = "results"
        
    }
    

}
